name: SMMetin
version: '${project.version}'
main: pl.stylowamc.smmetin.Smmetin
api-version: 1.19
softdepend: [Vault]
authors: [Styluś]
description: Plugin dodający bloki Metina które po zniszczeniu dają nagrody.

commands:
  metin:
    description: Zarządzanie Metinami
    usage: /<command> [spawn|tp|list|remove|removeall|statystyki|topka]
    aliases: [smmetin]
  metinrewards:
    description: Zarządzanie nagrodami Metinów
    usage: /<command>
    aliases: [metinnagrody, nagrodymetin]

permissions:
  smmetin.admin:
    description: Dostęp do wszystkich funkcji pluginu
    default: op
    children:
      smmetin.spawn: true
      smmetin.teleport: true
      smmetin.list: true
      smmetin.remove: true
      smmetin.removeall: true
      smmetin.stats.others: true
      smmetin.top: true
      smmetin.rewards: true
  smmetin.spawn:
    description: Pozwala na wymuszanie respienia Metinów
    default: op
  smmetin.teleport:
    description: Pozwala na teleportowanie się do Metinów
    default: op
  smmetin.list:
    description: Pozwala na wyświetlenie listy aktywnych Metinów
    default: op
  smmetin.remove:
    description: Pozwala na usuwanie Metinów
    default: op
  smmetin.removeall:
    description: Pozwala na usuwanie wszystkich Metinów
    default: op
  smmetin.stats.others:
    description: Pozwala na przeglądanie statystyk innych graczy
    default: op
  smmetin.top:
    description: Pozwala na przeglądanie rankingu graczy
    default: true
  smmetin.rewards:
    description: Pozwala na zarządzanie nagrodami Metinów
    default: op
